# Basic Information 
title: Qiping Wei
position: Ph.D. in Comp. Sci. & Eng.
affiliation: University of Texas at Arlington
affiliation_link: https://www.uta.edu/academics/schools-colleges/engineering/academics/departments/cse
affiliation_logo: ./assets/img/uta_icon_small1.jpg
email: qiping.wei (at) mavs.uta.edu
# email2: 

# Search Engine Optimization (SEO)
keywords: Qiping Wei, Wei Qiping, x Qiping
# canonical: 
description: Qiping Wei is a Ph.D. student at The University of Texas at Arlington (UTA).

# The option is used to enable the template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=7i_ZGlsAAAAJ&hl=en
cv_link: ./assets/img/CV_qiping.pdf
github_link: https://github.com/qiana0223/
# linkedin: xxx
# twitter: xxx

# Images 
avatar: ./assets/img/qiping1.png # change avatar1.jpg to qiping1.png
favicon: ./assets/img/favicon1.png
favicon_dark: ./assets/img/favicon1-dark.png

# Educations
bachelor_logo: ./assets/img/hust.jpg
master_logo: ./assets/img/uta_icon.jpg
phd_logo: ./assets/img/uta_icon.jpg

# Footnotes
#footnote: "2024 Qiping Wei"
#footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
#clustrmaps_id: PaNXfGbGqWkJPFgftLllF8IUcF-VRFKYKBMZ-BEXaa8

# The following files will be removed from the generated website.
#exclude:
#  - build.sh
#  - Gemfile
#  - Gemfile.lock
#  - README.md
#  - LICENSE
#  - CNAME
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CNAME
